title: Josh Wilburn
subtitle: Developer, trader, and all-around great guy
description: >- # this means to ignore newlines until "baseurl:"
  Josh Wilburn

url: "https://youngpascal.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /

# Edit these details

author_logo: personal.jpg
author: Josh Wilburn
author_bio: 
author_email: "josh@joshwilburn.me"
author_location: Houston, TX
author_website_url: "http://joshwilburn.me"

author_work_experiences:
            - company_name: United Engineers, Inc (Current)
              company_logo: uei.jpg
              company_url: https://www.unitede.com/
              designation: OSP Engineer
              description: Provide constructional and anayltical design of fiber and copper plant infrastrcture for AT&T.
              visibility: true
            - company_name: Byers Engineering
              company_logo: byers.jpg
              company_url: http://www.byers.com/
              designation: OSP Engineer
              description: Provided constructional and anayltical design of fiber and copper plant infrastrcture for AT&T.
              visibility: true
            - company_name: DTI (Drilling Technological Innovations)
              company_logo: dti-logo-2x.png
              company_url: https://www.dtillc.com/
              designation: Software Engineer
              description: Developed several ETL solutions for migrating data between ERPs and OEM products such as AutoCad. Developed SharePoint solutions to move paper processes to online workflows.
              visibility: true              

author_education_details:
              - college_logo: uh-logo.png
                college_name: University of Houston
                college_url: https://uh.edu
                college_degree: Computer Science
                description: Bachelor of Science
                visibility: true

author_project_details:
              - project_thumbnail: peercoin-leaf.png
                project_title: Peercoin
                project_description: Pioneer of the Proof of Stake cryptocurrency consensus protocol.
                project_url: https://github.com/peercoin/
                visibility: true
              - project_thumbnail: PeerAssets_icon.svg
                project_title: PeerAssets
                project_description: A simple blockchain based protocol which enables peers to issue and transact with tokens.
                project_url: https://github.com/PeerAssets
                visibility: true
              - project_thumbnail: PeerAssets_icon.svg
                project_title: PeerAssets API
                project_description: A dockerized minimalist API for PeerAssets using Flask in Python.
                project_url: https://github.com/PeerAssets/papi
                visibility: true
# social links
github_username:  youngpascal
linkedin_username: josh-wilburn


#for comments using disqus
#disqus_shortname: sujay-kundu

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url:

# formspree (contact form)
formspree_email: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _products
  - _includes/blog_newsletter.html
  - _includes/coding_activity.html
  - _includes/search.html
  - blog
  - _layouts/blog.html
  - _layouts/post.html
  - _layouts/product.html
  - _layouts/search.html
  - _layouts/contact.html
  - gallery
  - _posts

destination: ./build 